// Copyright (C) 2019-2024 Zilliz. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under the License.

/**
 * @file test_dense_vs_multivec.cc
 * @brief Compare Dense retrieval with Multi-Vector retrieval (ColBERT style)
 *
 * This test compares:
 * - Dense: Single vector per document, standard HNSW search
 * - Multi-Vector: Multiple vectors per document, MaxSim scoring
 *
 * Both are evaluated using the same ground truth labels.
 */

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <string>
#include <unordered_map>
#include <vector>

#include "catch2/catch_test_macros.hpp"
#include "nlohmann/json.hpp"
#include "knowhere/comp/brute_force.h"
#include "knowhere/comp/index_param.h"
#include "knowhere/dataset.h"
#include "knowhere/index/index_factory.h"

namespace {

// ============================================================================
// Configuration
// ============================================================================
const std::string DENSE_MODEL = "e5";  // Model used for dense embeddings

// File paths (generated by prepare_e5_dense.py)
const std::string MSMARCO_DENSE_DOCS = "msmarco_e5_docs.bin";
const std::string MSMARCO_DENSE_QUERIES = "msmarco_e5_queries.bin";
const std::string MSMARCO_DENSE_GT = "msmarco_e5_gt.bin";
const std::string MSMARCO_DENSE_GT_RELS = "msmarco_e5_gt_rels.bin";

const std::string SCIFACT_DENSE_DOCS = "scifact_e5_docs.bin";
const std::string SCIFACT_DENSE_QUERIES = "scifact_e5_queries.bin";
const std::string SCIFACT_DENSE_GT = "scifact_e5_gt.bin";
const std::string SCIFACT_DENSE_GT_RELS = "scifact_e5_gt_rels.bin";

const std::string LOTTE_DENSE_DOCS = "lotte_e5_docs.bin";
const std::string LOTTE_DENSE_QUERIES = "lotte_e5_queries.bin";
const std::string LOTTE_DENSE_GT = "lotte_e5_gt.bin";
const std::string LOTTE_DENSE_GT_RELS = "lotte_e5_gt_rels.bin";

const std::string TREC_COVID_DENSE_DOCS = "trec_covid_e5_docs.bin";
const std::string TREC_COVID_DENSE_QUERIES = "trec_covid_e5_queries.bin";
const std::string TREC_COVID_DENSE_GT = "trec_covid_e5_gt.bin";
const std::string TREC_COVID_DENSE_GT_RELS = "trec_covid_e5_gt_rels.bin";

// DocVQA paths (multimodal dense - supports MODEL_TAG env var)
constexpr int32_t MAX_DENSE_QUERIES = 100;  // Limit queries for faster testing

inline std::string GetDocvqaModelTag() {
    const char* env = std::getenv("MODEL_TAG");
    return env ? env : "qwen3vlemb2b";
}
inline std::string GetDocvqaDenseDocsPath() {
    const char* env = std::getenv("DOCVQA_DENSE_DOCS_PATH");
    return env ? env : "docvqa_" + GetDocvqaModelTag() + "_docs.bin";
}
inline std::string GetDocvqaDenseQueriesPath() {
    const char* env = std::getenv("DOCVQA_DENSE_QUERIES_PATH");
    return env ? env : "docvqa_" + GetDocvqaModelTag() + "_queries.bin";
}
inline std::string GetDocvqaDenseGTPath() {
    const char* env = std::getenv("DOCVQA_DENSE_GT_PATH");
    return env ? env : "docvqa_" + GetDocvqaModelTag() + "_gt.bin";
}
inline std::string GetDocvqaDenseGTRelsPath() {
    const char* env = std::getenv("DOCVQA_DENSE_GT_RELS_PATH");
    return env ? env : "docvqa_" + GetDocvqaModelTag() + "_gt_rels.bin";
}

// ============================================================================
// Data Loading Utilities
// ============================================================================

struct DenseData {
    std::vector<float> vectors;
    int32_t dim = 0;
    int64_t num_vectors = 0;

    bool
    LoadFromBinary(const std::string& path, int64_t max_vectors = -1) {
        std::ifstream file(path, std::ios::binary);
        if (!file) {
            printf("Cannot open binary file: %s\n", path.c_str());
            return false;
        }

        file.read(reinterpret_cast<char*>(&dim), sizeof(int32_t));
        file.read(reinterpret_cast<char*>(&num_vectors), sizeof(int64_t));

        int64_t original_count = num_vectors;
        if (max_vectors > 0 && num_vectors > max_vectors) {
            num_vectors = max_vectors;
        }

        vectors.resize(num_vectors * dim);
        file.read(reinterpret_cast<char*>(vectors.data()), vectors.size() * sizeof(float));

        file.close();
        if (original_count != num_vectors) {
            printf("Loaded %ld/%ld vectors, dim=%d from %s\n", num_vectors, original_count, dim, path.c_str());
        } else {
            printf("Loaded %ld vectors, dim=%d from %s\n", num_vectors, dim, path.c_str());
        }
        return true;
    }

    knowhere::DataSetPtr
    ToDataSet() const {
        float* data = new float[vectors.size()];
        std::memcpy(data, vectors.data(), vectors.size() * sizeof(float));

        auto ds = knowhere::GenDataSet(num_vectors, dim, data);
        ds->SetIsOwner(true);
        return ds;
    }
};

struct GTData {
    std::vector<std::vector<int64_t>> gt_pids;
    std::vector<std::unordered_map<int64_t, int>> gt_rels;
    bool has_graded_relevance = false;
    int64_t num_queries = 0;

    bool
    LoadFromBinary(const std::string& path, int64_t max_queries_limit = -1) {
        std::ifstream file(path, std::ios::binary);
        if (!file) {
            printf("Cannot open GT file: %s\n", path.c_str());
            return false;
        }

        int64_t total_queries;
        file.read(reinterpret_cast<char*>(&total_queries), sizeof(int64_t));

        num_queries = total_queries;
        if (max_queries_limit > 0 && num_queries > max_queries_limit) {
            num_queries = max_queries_limit;
        }
        gt_pids.resize(num_queries);

        for (int64_t i = 0; i < total_queries; ++i) {
            int64_t num_gt;
            file.read(reinterpret_cast<char*>(&num_gt), sizeof(int64_t));
            if (i < num_queries) {
                gt_pids[i].resize(num_gt);
                file.read(reinterpret_cast<char*>(gt_pids[i].data()), num_gt * sizeof(int64_t));
            } else {
                // Skip remaining GT data
                file.seekg(num_gt * sizeof(int64_t), std::ios::cur);
            }
        }

        file.close();

        // Build binary gt_rels (all rel=1)
        gt_rels.resize(num_queries);
        for (int64_t i = 0; i < num_queries; ++i) {
            for (auto pid : gt_pids[i]) {
                gt_rels[i][pid] = 1;
            }
        }

        if (total_queries != num_queries) {
            printf("Loaded GT for %ld/%ld queries\n", num_queries, total_queries);
        }
        PrintStats();
        return true;
    }

    bool
    LoadFromJSONL(const std::string& path) {
        std::ifstream file(path);
        if (!file) {
            printf("Cannot open JSONL GT file: %s\n", path.c_str());
            return false;
        }

        std::string line;
        while (std::getline(file, line)) {
            if (line.empty())
                continue;
            auto json = nlohmann::json::parse(line);

            if (!json.contains("gt_pids"))
                continue;

            std::vector<int64_t> pids;
            for (auto& p : json["gt_pids"]) {
                pids.push_back(p.get<int64_t>());
            }
            gt_pids.push_back(pids);

            std::unordered_map<int64_t, int> rels;
            if (json.contains("gt_rels")) {
                for (auto& [key, val] : json["gt_rels"].items()) {
                    rels[std::stoll(key)] = val.get<int>();
                }
            } else {
                for (auto pid : pids) {
                    rels[pid] = 1;
                }
            }
            gt_rels.push_back(rels);
        }

        num_queries = gt_pids.size();

        // Detect graded relevance
        for (auto& rels : gt_rels) {
            for (auto& [id, rel] : rels) {
                if (rel > 1) {
                    has_graded_relevance = true;
                    break;
                }
            }
            if (has_graded_relevance)
                break;
        }

        PrintStats();
        if (has_graded_relevance) {
            printf("Graded relevance: YES\n");
        }
        return true;
    }

    bool
    LoadRelsFromBinary(const std::string& path) {
        std::ifstream file(path, std::ios::binary);
        if (!file) {
            printf("Cannot open gt_rels file: %s\n", path.c_str());
            return false;
        }

        int64_t nq;
        file.read(reinterpret_cast<char*>(&nq), sizeof(int64_t));
        if (nq < num_queries) {
            printf("gt_rels query count too small: %ld vs %ld\n", nq, num_queries);
            return false;
        }

        // Overwrite gt_rels with graded data
        gt_rels.clear();
        gt_rels.resize(num_queries);

        for (int64_t i = 0; i < nq; ++i) {
            int64_t num_entries;
            file.read(reinterpret_cast<char*>(&num_entries), sizeof(int64_t));
            if (i < num_queries) {
                for (int64_t j = 0; j < num_entries; ++j) {
                    int64_t pid;
                    int32_t rel;
                    file.read(reinterpret_cast<char*>(&pid), sizeof(int64_t));
                    file.read(reinterpret_cast<char*>(&rel), sizeof(int32_t));
                    gt_rels[i][pid] = rel;
                }
            } else {
                // Skip remaining entries
                file.seekg(num_entries * (sizeof(int64_t) + sizeof(int32_t)), std::ios::cur);
            }
        }

        // Detect graded relevance
        for (auto& rels : gt_rels) {
            for (auto& [id, rel] : rels) {
                if (rel > 1) {
                    has_graded_relevance = true;
                    break;
                }
            }
            if (has_graded_relevance)
                break;
        }

        printf("Loaded graded relevance from %s\n", path.c_str());
        if (has_graded_relevance) {
            printf("Graded relevance: YES\n");
        }
        return true;
    }

    void
    PrintStats() const {
        int64_t total_gt = 0, min_gt = INT64_MAX, max_gt = 0;
        for (const auto& gt : gt_pids) {
            total_gt += gt.size();
            min_gt = std::min(min_gt, (int64_t)gt.size());
            max_gt = std::max(max_gt, (int64_t)gt.size());
        }
        printf("Loaded GT for %ld queries, GT/query: min=%ld, max=%ld, avg=%.1f\n", num_queries, min_gt, max_gt,
               (double)total_gt / num_queries);
    }
};

// Timer utility
class StopWatch {
 public:
    StopWatch() : start_(std::chrono::high_resolution_clock::now()) {
    }

    double
    elapsed_seconds() const {
        auto now = std::chrono::high_resolution_clock::now();
        return std::chrono::duration<double>(now - start_).count();
    }

    void
    reset() {
        start_ = std::chrono::high_resolution_clock::now();
    }

 private:
    std::chrono::time_point<std::chrono::high_resolution_clock> start_;
};

// Calculate E2E Recall
float
CalcE2ERecall(const int64_t* result_ids, int32_t k, const std::vector<std::vector<int64_t>>& gt_pids,
              int64_t num_queries) {
    float total_recall = 0.0f;
    int64_t valid_queries = 0;

    for (int64_t q = 0; q < num_queries; ++q) {
        const auto& gt = gt_pids[q];
        if (gt.empty())
            continue;

        int64_t hits = 0;
        for (int32_t i = 0; i < k; ++i) {
            int64_t id = result_ids[q * k + i];
            if (std::find(gt.begin(), gt.end(), id) != gt.end()) {
                hits++;
            }
        }

        total_recall += (float)hits / gt.size();
        valid_queries++;
    }

    return valid_queries > 0 ? total_recall / valid_queries : 0.0f;
}

// Calculate nDCG@k with graded relevance (gain = 2^rel - 1)
float
CalcNDCG(const int64_t* result_ids, int32_t k, const std::vector<std::unordered_map<int64_t, int>>& gt_rels,
         int64_t num_queries) {
    float total_ndcg = 0.0f;
    int64_t valid_queries = 0;

    for (int64_t q = 0; q < num_queries; ++q) {
        const auto& rels = gt_rels[q];
        if (rels.empty())
            continue;

        double dcg = 0.0;
        for (int32_t i = 0; i < k; ++i) {
            int64_t id = result_ids[q * k + i];
            auto it = rels.find(id);
            if (it != rels.end()) {
                dcg += (std::pow(2.0, it->second) - 1.0) / std::log2(i + 2.0);
            }
        }

        // IDCG: sort all relevance grades descending
        std::vector<int> sorted_rels;
        sorted_rels.reserve(rels.size());
        for (const auto& [id, rel] : rels) {
            sorted_rels.push_back(rel);
        }
        std::sort(sorted_rels.rbegin(), sorted_rels.rend());

        double idcg = 0.0;
        int ideal_count = std::min((int)sorted_rels.size(), (int)k);
        for (int i = 0; i < ideal_count; ++i) {
            idcg += (std::pow(2.0, sorted_rels[i]) - 1.0) / std::log2(i + 2.0);
        }

        total_ndcg += idcg > 0 ? (float)(dcg / idcg) : 0.0f;
        valid_queries++;
    }

    return valid_queries > 0 ? total_ndcg / valid_queries : 0.0f;
}

// Calculate MRR@k
float
CalcMRR(const int64_t* result_ids, int32_t k, const std::vector<std::vector<int64_t>>& gt_pids,
        int64_t num_queries) {
    float total_rr = 0.0f;
    int64_t valid_queries = 0;

    for (int64_t q = 0; q < num_queries; ++q) {
        const auto& gt = gt_pids[q];
        if (gt.empty())
            continue;

        for (int32_t i = 0; i < k; ++i) {
            int64_t id = result_ids[q * k + i];
            if (std::find(gt.begin(), gt.end(), id) != gt.end()) {
                total_rr += 1.0f / (i + 1);
                break;
            }
        }
        valid_queries++;
    }

    return valid_queries > 0 ? total_rr / valid_queries : 0.0f;
}

// Run Dense retrieval test
void
RunDenseTest(const std::string& dataset_name, const std::string& docs_path, const std::string& queries_path,
             const std::string& gt_path, const std::vector<int32_t>& topk_values,
             const std::string& gt_rels_path = "", int64_t max_queries = -1) {
    printf("\n");
    printf("================================================================\n");
    printf("Dense Retrieval Test: %s\n", dataset_name.c_str());
    printf("================================================================\n");

    // Load data
    DenseData docs, queries;
    GTData gt;

    if (!docs.LoadFromBinary(docs_path)) {
        printf("Failed to load documents, skipping test\n");
        return;
    }

    if (!queries.LoadFromBinary(queries_path, max_queries)) {
        printf("Failed to load queries, skipping test\n");
        return;
    }

    if (!gt.LoadFromBinary(gt_path, max_queries)) {
        printf("Failed to load GT, skipping test\n");
        return;
    }

    // Load graded relevance if available
    if (!gt_rels_path.empty()) {
        gt.LoadRelsFromBinary(gt_rels_path);
    }

    int32_t dim = docs.dim;
    int64_t num_docs = docs.num_vectors;
    int64_t num_queries = queries.num_vectors;
    printf("\nDataset: %ld docs, %ld queries, dim=%d\n", num_docs, num_queries, dim);

    int32_t max_k = *std::max_element(topk_values.begin(), topk_values.end());
    auto doc_ds = docs.ToDataSet();
    auto query_ds = queries.ToDataSet();

    // ========== BruteForce Search ==========
    printf("\n[Dense BruteForce] Computing results...\n");
    fflush(stdout);

    std::vector<float> bf_recalls(topk_values.size());
    float bf_ndcg10 = 0.0f, bf_mrr10 = 0.0f;
    double bf_total_time = 0;

    for (size_t i = 0; i < topk_values.size(); ++i) {
        int32_t k = topk_values[i];

        knowhere::Json bf_conf;
        bf_conf[knowhere::meta::METRIC_TYPE] = "IP";
        bf_conf[knowhere::meta::TOPK] = k;

        StopWatch sw_bf;
        auto bf_result = knowhere::BruteForce::Search<knowhere::fp32>(doc_ds, query_ds, bf_conf, nullptr);
        bf_total_time += sw_bf.elapsed_seconds();

        if (!bf_result.has_value()) {
            printf("BruteForce search failed for k=%d\n", k);
            continue;
        }

        const int64_t* bf_ids = bf_result.value()->GetIds();
        bf_recalls[i] = CalcE2ERecall(bf_ids, k, gt.gt_pids, num_queries);

        // nDCG@10/MRR@10 from first k >= 10 (no rerank, so top-10 is same for any k >= 10)
        if (k >= 10 && bf_ndcg10 == 0.0f) {
            bf_ndcg10 = CalcNDCG(bf_ids, 10, gt.gt_rels, num_queries);
            bf_mrr10 = CalcMRR(bf_ids, 10, gt.gt_pids, num_queries);
        }
    }

    printf("[Dense BruteForce] Time: %.3f s\n", bf_total_time);
    printf("[Dense BruteForce] Recall (vs GT): ");
    for (size_t i = 0; i < topk_values.size(); ++i) {
        printf("@%d=%.1f%% ", topk_values[i], bf_recalls[i] * 100);
    }
    printf("\n");
    printf("[Dense BruteForce] nDCG@10=%.4f, MRR@10=%.4f\n", bf_ndcg10, bf_mrr10);
    fflush(stdout);

    // ========== Build HNSW index ==========
    printf("\n[Dense HNSW] Building index...\n");
    fflush(stdout);

    knowhere::Json build_conf;
    build_conf[knowhere::meta::METRIC_TYPE] = "IP";  // Inner Product (vectors are normalized)
    build_conf[knowhere::meta::DIM] = dim;
    build_conf[knowhere::indexparam::HNSW_M] = 16;
    build_conf[knowhere::indexparam::EFCONSTRUCTION] = 100;

    auto version = knowhere::Version::GetCurrentVersion().VersionNumber();
    auto index = knowhere::IndexFactory::Instance().Create<knowhere::fp32>(knowhere::IndexEnum::INDEX_HNSW, version);

    if (!index.has_value()) {
        printf("Failed to create HNSW index\n");
        return;
    }

    StopWatch sw_build;
    auto build_status = index.value().Build(doc_ds, build_conf);
    double build_time = sw_build.elapsed_seconds();

    if (build_status != knowhere::Status::success) {
        printf("Build failed: %s\n", knowhere::Status2String(build_status).c_str());
        return;
    }
    printf("[Dense HNSW] Build time: %.3f s\n", build_time);

    // ========== Search with HNSW ==========
    printf("[Dense HNSW] Searching...\n");
    fflush(stdout);

    std::vector<float> e2e_recalls(topk_values.size());
    std::vector<double> latencies(topk_values.size());
    float ndcg10 = 0.0f, mrr10 = 0.0f;

    knowhere::Json search_conf;
    search_conf[knowhere::meta::METRIC_TYPE] = "IP";
    search_conf[knowhere::indexparam::EF] = std::max(128, max_k * 2);

    for (size_t i = 0; i < topk_values.size(); ++i) {
        int32_t k = topk_values[i];
        search_conf[knowhere::meta::TOPK] = k;

        StopWatch sw_search;
        auto result = index.value().Search(query_ds, search_conf, nullptr);
        double search_time = sw_search.elapsed_seconds();

        if (!result.has_value()) {
            printf("Search failed for k=%d\n", k);
            continue;
        }

        const int64_t* ids = result.value()->GetIds();
        e2e_recalls[i] = CalcE2ERecall(ids, k, gt.gt_pids, num_queries);
        // nDCG@10/MRR@10 from first k >= 10 (no rerank, so top-10 is same for any k >= 10)
        if (k >= 10 && ndcg10 == 0.0f) {
            ndcg10 = CalcNDCG(ids, 10, gt.gt_rels, num_queries);
            mrr10 = CalcMRR(ids, 10, gt.gt_pids, num_queries);
        }
        latencies[i] = search_time * 1000 / num_queries;  // ms per query
    }

    // ========== Print Results ==========
    printf("\n[Dense Results] (EF=%d):\n", std::max(128, max_k * 2));
    printf("| K    | BF Recall  | HNSW Recall | Latency (ms/q) |\n");
    printf("|------|------------|-------------|----------------|\n");
    for (size_t i = 0; i < topk_values.size(); ++i) {
        printf("| %4d | %9.1f%% | %10.1f%% | %14.2f |\n", topk_values[i], bf_recalls[i] * 100,
               e2e_recalls[i] * 100, latencies[i]);
    }
    printf("BruteForce  nDCG@10=%.4f, MRR@10=%.4f\n", bf_ndcg10, bf_mrr10);
    printf("HNSW        nDCG@10=%.4f, MRR@10=%.4f\n", ndcg10, mrr10);
    printf("\n");
    fflush(stdout);
}

}  // namespace

// ============================================================================
// Test Cases
// ============================================================================

TEST_CASE("Dense vs Multi-Vector: MS MARCO", "[dense_vs_multivec][msmarco]") {
    // Check if dense data files exist
    {
        std::ifstream docs_file(MSMARCO_DENSE_DOCS);
        std::ifstream queries_file(MSMARCO_DENSE_QUERIES);
        std::ifstream gt_file(MSMARCO_DENSE_GT);

        if (!docs_file.good() || !queries_file.good() || !gt_file.good()) {
            printf("\n");
            printf("=============================================================\n");
            printf("Dense embedding files not found. Please prepare the data first.\n");
            printf("Expected files:\n");
            printf("  - %s\n", MSMARCO_DENSE_DOCS.c_str());
            printf("  - %s\n", MSMARCO_DENSE_QUERIES.c_str());
            printf("  - %s\n", MSMARCO_DENSE_GT.c_str());
            printf("\n");
            printf("Generate dense embeddings:\n");
            printf("  python scripts/prepare_e5_dense.py --input-dir . --output-dir . --dataset msmarco\n");
            printf("=============================================================\n");
            SKIP("Dense embedding files not found");
            return;
        }
    }

    std::vector<int32_t> topk_values = {10, 20, 50, 100};
    RunDenseTest("MS MARCO", MSMARCO_DENSE_DOCS, MSMARCO_DENSE_QUERIES, MSMARCO_DENSE_GT, topk_values,
                 MSMARCO_DENSE_GT_RELS);
}

TEST_CASE("Dense vs Multi-Vector: SciFact", "[dense_vs_multivec][scifact]") {
    {
        std::ifstream docs_file(SCIFACT_DENSE_DOCS);
        std::ifstream queries_file(SCIFACT_DENSE_QUERIES);
        std::ifstream gt_file(SCIFACT_DENSE_GT);

        if (!docs_file.good() || !queries_file.good() || !gt_file.good()) {
            printf("\n");
            printf("=============================================================\n");
            printf("SciFact dense files not found. Prepare with:\n");
            printf("  python scripts/prepare_e5_dense.py --input-dir . --output-dir . --dataset scifact\n");
            printf("=============================================================\n");
            SKIP("SciFact dense files not found");
            return;
        }
    }

    std::vector<int32_t> topk_values = {10, 20, 50, 100};
    RunDenseTest("SciFact", SCIFACT_DENSE_DOCS, SCIFACT_DENSE_QUERIES, SCIFACT_DENSE_GT, topk_values,
                 SCIFACT_DENSE_GT_RELS);
}

TEST_CASE("Dense vs Multi-Vector: LoTTE", "[dense_vs_multivec][lotte]") {
    {
        std::ifstream docs_file(LOTTE_DENSE_DOCS);
        std::ifstream queries_file(LOTTE_DENSE_QUERIES);
        std::ifstream gt_file(LOTTE_DENSE_GT);

        if (!docs_file.good() || !queries_file.good() || !gt_file.good()) {
            printf("\n");
            printf("=============================================================\n");
            printf("LoTTE dense files not found. Prepare with:\n");
            printf("  python scripts/prepare_e5_dense.py --input-dir . --output-dir . --dataset lotte\n");
            printf("=============================================================\n");
            SKIP("LoTTE dense files not found");
            return;
        }
    }

    std::vector<int32_t> topk_values = {10, 20, 50, 100};
    RunDenseTest("LoTTE", LOTTE_DENSE_DOCS, LOTTE_DENSE_QUERIES, LOTTE_DENSE_GT, topk_values,
                 LOTTE_DENSE_GT_RELS);
}

TEST_CASE("Dense vs Multi-Vector: TREC-COVID", "[dense_vs_multivec][trec_covid]") {
    {
        std::ifstream docs_file(TREC_COVID_DENSE_DOCS);
        std::ifstream queries_file(TREC_COVID_DENSE_QUERIES);
        std::ifstream gt_file(TREC_COVID_DENSE_GT);

        if (!docs_file.good() || !queries_file.good() || !gt_file.good()) {
            printf("\n");
            printf("=============================================================\n");
            printf("TREC-COVID dense files not found. Prepare with:\n");
            printf("  python scripts/prepare_e5_dense.py --input-dir . --output-dir . --dataset trec_covid\n");
            printf("=============================================================\n");
            SKIP("TREC-COVID dense files not found");
            return;
        }
    }

    std::vector<int32_t> topk_values = {10, 20, 50, 100};
    RunDenseTest("TREC-COVID", TREC_COVID_DENSE_DOCS, TREC_COVID_DENSE_QUERIES, TREC_COVID_DENSE_GT, topk_values,
                 TREC_COVID_DENSE_GT_RELS);
}

TEST_CASE("Dense vs Multi-Vector: DocVQA", "[dense_vs_multivec][docvqa]") {
    std::string docs_path = GetDocvqaDenseDocsPath();
    std::string queries_path = GetDocvqaDenseQueriesPath();
    std::string gt_path = GetDocvqaDenseGTPath();
    std::string gt_rels_path = GetDocvqaDenseGTRelsPath();

    {
        std::ifstream docs_file(docs_path);
        std::ifstream queries_file(queries_path);
        std::ifstream gt_file(gt_path);

        if (!docs_file.good() || !queries_file.good() || !gt_file.good()) {
            printf("\n");
            printf("=============================================================\n");
            printf("DocVQA dense files not found. Prepare with:\n");
            printf("  python scripts/prepare_docvqa_multimodal.py --output-dir . --model Qwen/Qwen3-VL-Embedding-2B\n");
            printf("Expected files:\n");
            printf("  - %s\n", docs_path.c_str());
            printf("  - %s\n", queries_path.c_str());
            printf("  - %s\n", gt_path.c_str());
            printf("=============================================================\n");
            SKIP("DocVQA dense files not found");
            return;
        }
    }

    std::vector<int32_t> topk_values = {10};  // Small dataset (500 docs), only test recall@10
    std::string model_name = "DocVQA (" + GetDocvqaModelTag() + ")";
    RunDenseTest(model_name, docs_path, queries_path, gt_path, topk_values, gt_rels_path, MAX_DENSE_QUERIES);
}

TEST_CASE("Dense vs Multi-Vector: Summary Comparison", "[dense_vs_multivec][summary]") {
    printf("\n");
    printf("================================================================\n");
    printf("Dense vs Multi-Vector Comparison Summary\n");
    printf("================================================================\n");
    printf("\n");
    printf("To compare Dense and Multi-Vector retrieval:\n");
    printf("\n");
    printf("1. Prepare Multi-Vector (ColBERT) data:\n");
    printf("   python scripts/prepare_msmarco_with_gt.py --output-dir .\n");
    printf("   python scripts/prepare_scifact_with_gt.py --output-dir .\n");
    printf("   python scripts/prepare_lotte_with_gt.py --output-dir .\n");
    printf("   python scripts/prepare_trec_covid_colbertv2.py --output-dir .\n");
    printf("\n");
    printf("2. Prepare Dense embeddings (E5-base-v2):\n");
    printf("   python scripts/prepare_e5_dense.py --dataset msmarco --input-dir . --output-dir .\n");
    printf("   python scripts/prepare_e5_dense.py --dataset scifact --input-dir . --output-dir .\n");
    printf("   python scripts/prepare_e5_dense.py --dataset lotte --input-dir . --output-dir .\n");
    printf("   python scripts/prepare_e5_dense.py --dataset trec_covid --input-dir . --output-dir .\n");
    printf("\n");
    printf("3. Run tests:\n");
    printf("   ./tests/ut/knowhere_tests '[msmarco_emb_list]'      # Multi-Vector\n");
    printf("   ./tests/ut/knowhere_tests '[dense_vs_multivec]'     # Dense\n");
    printf("\n");
    printf("With random sampling (unbiased), ColBERTv2 should outperform Dense E5.\n");
    printf("Dense is faster and has smaller index size.\n");
    printf("\n");
}
